name: "Deploy to Cloudflare worker"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v4"
      - name: "Setup pnpm"
        uses: "pnpm/action-setup@v4.0.0"
      - name: "Use Node.js"
        uses: "actions/setup-node@v4"
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: "Install node dependencies"
        run: "pnpm install --frozen-lockfile"

      - name: "Build"
        env:
          BUILD_BRANCH: "${{ github.head_ref }}"
        run: "pnpm build"

      - name: "Deploy to Cloudflare (production)"
        if: "${{ github.event_name == 'push' }}"
        env:
          CLOUDFLARE_ACCOUNT_ID: "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"
          CLOUDFLARE_API_TOKEN: "${{ secrets.CLOUDFLARE_API_TOKEN }}"
        run: |
          pnpm exec wrangler deploy

      - name: "Deploy to Cloudflare (preview)"
        if: "${{ github.event_name == 'pull_request' }}"
        env:
          BRANCH_NAME: "${{ github.head_ref }}"
          MESSAGE:
            "Commit = ${{ github.sha }} Branch = ${{ github.head_ref }} Actor =
            ${{ github.actor }}"
          CLOUDFLARE_ACCOUNT_ID: "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"
          CLOUDFLARE_API_TOKEN: "${{ secrets.CLOUDFLARE_API_TOKEN }}"
        run: |
          pnpm exec wrangler versions upload --tag "$BRANCH_NAME" --message "$MESSAGE"
