name: "Lint files"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v4"
      - name: "Read Node.js version"
        id: "node_version"
        run: |
          echo "NODE_VERSION=$(cat .node-version)" >> $GITHUB_OUTPUT
      - name: "Setup pnpm"
        uses: "pnpm/action-setup@v3.0.0"
        with:
          version: "8"
      - name: "Use Node.js"
        uses: "actions/setup-node@v4"
        with:
          node-version: "${{ steps.node_version.outputs.NODE_VERSION }}"
          cache: "pnpm"

      - name: "Install node dependencies"
        run: "pnpm install --frozen-lockfile"

      - name: "Cache eslint"
        uses: "actions/cache@v4"
        with:
          path: ".eslintcache"
          key: "${{ runner.os }}-eslint"

      - name: "Run lint"
        run: "pnpm run lint"

      - name: "Run fmt check"
        run: "pnpm run fmt --check"

      - name: "Run typecheck"
        run: "pnpm run typecheck"
